version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    networks:
      - backend-network
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
      OPENAI_KEY: ${OPENAI_KEY}
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - backend-network
    restart: always  # Política de reinicio

networks:
  backend-network:

volumes:
  pgdata:
